apiVersion: batch/v1
kind: Job
metadata:
  name: odh-ossm-init-job
spec:
  template:
    spec:
      containers:
      - name: odh-ossm-init-job
        image: quay.io/openshift/origin-cli
        command: ["/bin/bash", "-c", "--"]
        args:
          - |
            etcdpasswordexists=$(oc get secrets -o name | grep etcd-passwords || echo "false")
            modelservingetcdexists=$(oc get secrets -o name | grep model-serving-etcd || echo "false")
            export CLIENT_SECRET=$(hexdump -vn32 -e'8/8 "%08X" 1 "\n"' /dev/urandom)
            export CLIENT_HMAC=$(hexdump -vn32 -e'8/8 "%08X" 1 "\n"' /dev/urandom)
            # tmp
            echo $CLIENT_SECRET
            echo $CLIENT_HMAC
            ls -l /etc/cfg-map
            kubectl apply -f etc/cfg-map/authconfig.yaml -n opendatahub

            clusterdomain=$(kubectl get ingress.config.openshift.io cluster -o 'jsonpath={.spec.domain}')
            echo $clusterdomain

            endpoint=$(kubectl -n istio-system run oidc-config --attach --rm --restart=Never -q --image=curlimages/curl -- https://kubernetes.default.svc/.well-known/oauth-authorization-server -sS -k)
            echo $endpoint

            function subst() { eval echo -E "$2"; }
            mapfile

            exit 0
            fi
        volumeMounts:
          - name: config-volume
            mountPath: /etc/cfg-map
      volumes:
      - name: config-volume
        configMap:
          name: mounting-configmap
      restartPolicy: Never
      serviceAccountName: init-job-serviceaccount