apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: istio-system
# Expects maistra-operator to be installed 
resources:
- namespace.yaml
- cert-secret.yaml
- control-plane.yaml
- proxy/auth-policy.yaml
- proxy/filter-propagate-token.yaml
- init-job.yaml
- init-job-rbac/job-cluster-role.yaml
- init-job-rbac/job-rolebinding.yaml
- init-job-rbac/job-sa.yaml

patches:
- path: patch-control-plane-mount-oauth2-secrets.yaml
  target:
    kind: ServiceMeshControlPlane
    name: basic
    namespace: istio-system
- path: patch-control-plane-external-provider.yaml
  target:
    kind: ServiceMeshControlPlane
    name: basic
    namespace: istio-system

configMapGenerator:
  - name: mounting-configmap
    files:
      - resource-templates/filter-oauth2.yaml
      - resource-templates/oauth-configmap.yaml
      - resource-templates/oauth-client.yaml
      - resource-templates/gateway-route.yaml
      - resource-templates/authconfig.yaml

generatorOptions:
  disableNameSuffixHash: true
