apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: istio-system
# Expects maistra-operator to be installed 
resources:
- namespace.yaml
- cert-secret.yaml
- control-plane.yaml
- proxy/auth-policy.yaml
- proxy/filter-propagate-token.yaml
- init-job.yaml

bases:
- ../init-job

patches:
- path: patch-control-plane-mount-oauth2-secrets.yaml
  target:
    kind: ServiceMeshControlPlane
    name: basic
    namespace: istio-system
- path: patch-control-plane-external-provider.yaml
  target:
    kind: ServiceMeshControlPlane
    name: basic
    namespace: istio-system

configMapGenerator:
  - name: mounting-configmap
    files:
      - proxy/filter-oauth2.yaml
      - cfg-map/oauth-configmap.yaml
      - cfg-map/oauth-client.yaml
      - cfg-map/gateway-route.yaml
      - cfg-map/authconfig.yaml

generatorOptions:
  disableNameSuffixHash: true
