apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# sortOptions:
#   order: fifo # otherwise ServiceMeshMember will be created after the deployment and thus istio will not inject sidecar proxy
resources:
- namespace.yaml

