apiVersion: authorino.kuadrant.io/v1beta1
kind: AuthConfig
metadata:
  name: odh-dashboard-protection
  labels:
    authorino/topic: istio
spec:
  hosts:
  # TODO add more hosts
  # TODO how to make it dynamic?
  # - opendatahub-odh-gateway-525eca1d5089dbdc-istio-system.apps-crc.testing
  - opendatahub-odh-gateway-525eca1d5089dbdc-istio-system.apps-crc.testing
  identity:
  - name: service-accounts
    kubernetes:
      audiences: 
      - "https://kubernetes.default.svc"
  authorization:
  - name: k8s-rbac
    kubernetes:
      user:
        valueFrom: { authJSON: auth.identity.sub }
  # - name: check-openshift-group
  #   json:
  #     rules:
  #     - selector: auth.identity.groups
  #       operator: incl
  #       value: odh-dashboard
  response:
  - name: x-auth-data
    json:
      properties:
      - name: username
        valueFrom: { authJSON: auth.identity.username }
  denyWith:
      unauthorized:
        message:
          value: "Sorry, but no, sorry!"
      # TODO needs better OAauth/redirect understanding on my end if it would work at all...
      unauthenticated:
        code: 302
        headers:
        - name: Location
          value: https://oauth-openshift.apps-crc.testing/oauth/authorize?client_id=odh&redirect_uri=https%3A%2F%2Fopendatahub-odh-gateway-525eca1d5089dbdc-istio-system.apps-crc.testing%2Foauth%2Fcallback&response_type=token&scope=user%3Afull
        - name: x-auth-pipeline
          value: authorino-odh-dashboard-protectioncrc
