apiVersion: authorino.kuadrant.io/v1beta1
kind: AuthConfig
metadata:
  name: odh-dashboard-protection
  labels:
    authorino/topic: odh
spec:
  hosts:
  # TODO add more hosts
  # TODO how to make it dynamic?
  # - opendatahub-odh-gateway-525eca1d5089dbdc-istio-system.apps-crc.testing
  - opendatahub-odh-gateway-525eca1d5089dbdc-istio-system.apps-crc.testing
  identity:
  - name: service-accounts
    kubernetes:
      audiences: 
      - "https://kubernetes.default.svc"
  authorization:
  - name: k8s-rbac
    kubernetes:
      user:
        valueFrom: { authJSON: auth.identity.sub }
  # - name: check-openshift-group
  #   json:
  #     rules:
  #     - selector: auth.identity.groups
  #       operator: incl
  #       value: odh-dashboard
  response:
  - name: x-auth-data
    json:
      properties:
      - name: username
        valueFrom: { authJSON: auth.identity.username }