apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: auth-provider
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: auth-service-cert
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8180
  selector:
    app: auth-service