apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: istio-system
# Expects maistra-operator to be installed 
resources:
- namespace.yaml
- cert-secret.yaml
- control-plane.yaml
- gateway-route.yaml
- proxy/filter-oauth2.yaml
- proxy/filter-propagate-token.yaml

patches:
- path: patch-control-plane-mount-oauth2-secrets.yaml
  target:
    kind: ServiceMeshControlPlane
    name: basic
    namespace: istio-system
- path: patch-control-plane-external-provider.yaml
  target:
    kind: ServiceMeshControlPlane
    name: basic
    namespace: istio-system