apiVersion: maistra.io/v2
kind: ServiceMeshControlPlane
metadata:
  name: basic
  namespace: istio-system
spec:
  techPreview:
    meshConfig:
      extensionProviders:
      - name: odh-auth-provider
        envoyExtAuthzGrpc:
          service: authorino-authorino-authorization.auth-provider.svc.cluster.local
          port: 50051