---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  - serviceaccounts
  - services
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - config.openshift.io
  resources:
  - proxies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kubeflow.org
  resources:
  - notebooks
  verbs:
  - get
  - list
  - patch
  - watch
- apiGroups:
  - kubeflow.org
  resources:
  - notebooks/finalizers
  verbs:
  - update
- apiGroups:
  - kubeflow.org
  resources:
  - notebooks/status
  verbs:
  - get
- apiGroups:
  - networking.k8s.io
  resources:
  - networkpolicies
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - route.openshift.io
  resources:
  - routes
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - maistra.io
  resources:
  - servicemeshmembers
  - servicemeshcontrolplanes
  - servicemeshmemberroles
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
  - use # TODO check if only this is needed
- apiGroups:
  - authorino.kuadrant.io
  resources:
  - authconfigs
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
