kind: OAuthClient           
apiVersion: oauth.openshift.io/v1
metadata:
 name: odh
secret: "$CLIENT_SECRET" # gitleaks:allow
redirectURIs:
- "https://opendatahub-odh-gateway-istio-system.$DOMAIN"
grantMethod: prompt