apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- smm.yaml
- namespace.yaml
namespace: opendatahub
vars:
  - name: namespace
    objref:
      kind: ConfigMap
      name: odh-common-config
      apiVersion: v1
    fieldref:
      fieldpath: metadata.namespace