resources:
  - manager.yaml
  - service-account.yaml
  - service.yaml
configMapGenerator:
  - name: config
    literals:
      - USE_ISTIO=true
      - ISTIO_GATEWAY=notebook-gateway
generatorOptions:
  disableNameSuffixHash: true
