kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: auth-service
  namespace: $AUTH_NS
subjects:
  - kind: ServiceAccount
    name: auth-service
    namespace: auth-provider
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: auth-service
