kind: ServiceAccount
apiVersion: v1
metadata:
  name: auth-service
  annotations:
    serviceaccounts.openshift.io/oauth-redirecturi.first:  "oauth/callback"
    serviceaccounts.openshift.io/oauth-redirectreference.first: >-
      {"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"oauth-client"}}