apiVersion: maistra.io/v2
kind: ServiceMeshControlPlane
metadata:
  name: basic
  namespace: istio-system
spec:
  version: v2.3
  proxy:
    accessLogging:
      file:
        name: /dev/stdout 
    injection:
      autoInject: true
    runtime:
      container:
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 129Mi
  tracing:
    type: Jaeger
    sampling: 10000
  addons:
    jaeger: 
      name: jaeger
      install:
        storage:
          type: Memory
    kiali:
      enabled: true
      name: kiali
  techPreview:
    meshConfig:
      extensionProviders:
        - name: proxy
          envoyExtAuthzHttp:
            service: proxy.ext-auth.svc.cluster.local
            port: 80
            timeout: 1.5s
            includeHeadersInCheck: ["authorization", "cookie"]
            headersToUpstreamOnAllow: ["x-forwarded-access-token", "authorization", "path", "x-auth-request-user", "x-auth-request-email", "x-auth-request-access-token"]
            headersToDownstreamOnDeny: ["content-type", "set-cookie"]
