apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: istio-system
# Expects maistra-operator to be installed 
resources:
- namespace.yaml
- cert-secret.yaml
- control-plane.yaml
