apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: init-job-role
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
      - configmaps
      - authconfigs
      - routes
      - oauthclients
      - envoyfilters
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch