apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: init-job-role
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
      - configmaps
      - authconfigs
      - routes
      - oauthclients
      - envoyfilters
      - pods
      - pods/log
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups: 
      - "config.openshift.io"
    resources:
      - ingresses
    verbs:
      - get