apiVersion: maistra.io/v2
kind: ServiceMeshControlPlane
metadata:
  name: basic
  namespace: istio-system
spec:
  gateways:
    ingress:
      volumes:
        - volume:
            configMap:
              name: istio-odh-oauth2
              optional: true
          volumeMount:
            name: odh-oauth2-tokens
            mountPath: "/etc/istio/odh-oauth2"
            readOnly: true
